# .github/workflows/ci-vulnerable.yml
name: CI (VULNERABLE EXAMPLE)

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Runs with the base repository's context on PRs, including from forks
    runs-on: ubuntu-latest

    # Overly broad permissions allow write actions against the repo
    permissions:
      contents: write        # dangerous on pull_request_target
      pull-requests: write   # also risky

    env:
      # Secrets are available in this context and will be reachable by attacker-controlled code
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout PR code (DANGEROUS)
        uses: actions/checkout@v4
        with:
          # Explicitly pulls the contributor's fork and branch (attacker-controlled)
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          # Leaves write-capable credentials in the repo working copy
          persist-credentials: true

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish artifact (runs with write token)
        run: |
          echo "Pretend we publish or tag a release here"
          # Attacker-controlled code above can already run with write and secrets
